###
### BUILD PIPELINE
###
kind: pipeline
type: kubernetes
name: build

trigger:
  event: [push, pull_request, tags, tag]
  branch: [main, develop, refs/tags/*]
steps:
  - name: builder
    image: plugins/docker
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    settings:
      registry: quay.io
      insecure: true
      repo: quay.io/zebbra/neops-web-sdk
      purge: false
      tags: builder
      target: builder
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      build_args:
        - NEOPS_VERSION: ${DRONE_COMMIT_SHA}
      build_args_from_env:
        - NPM_TOKEN
      cache_from:
        - quay.io/zebbra/neops-web-sdk:builder

  - name: image_build
    image: plugins/docker
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    settings:
      registry: quay.io
      insecure: true
      repo: quay.io/zebbra/neops-web-sdk
      purge: false
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      build_args:
        - NEOPS_VERSION: ${DRONE_COMMIT_SHA}
      build_args_from_env:
        - NPM_TOKEN
      cache_from:
        - quay.io/zebbra/neops-web-sdk
        - quay.io/zebbra/neops-web-sdk:builder

---

kind: pipeline
type: kubernetes
name: publish


trigger:
  event: [tag]

depends_on:
  - build

steps:
  - name: imagebuild
    image: plugins/docker
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    settings:
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      registry: quay.io
      repo: quay.io/zebbra/neops-web-sdk
      build_args:
        - NEOPS_VERSION: ${DRONE_TAG}
      build_args_from_env:
        - NPM_TOKEN
      auto_tag: true
      cache_from:
        - quay.io/zebbra/neops-web-sdk:builder
        - quay.io/zebbra/neops-web-sdk:${DRONE_COMMIT_SHA:0:7}
      mtu: 1316

  - name: make
    image: node:16
    environment:
      NEOPS_VERSION: ${DRONE_TAG}
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - echo //npm.pkg.github.com/:_authToken=$${NPM_TOKEN:?} >> ~/.npmrc
      - npm config set @zebbra:registry https://npm.pkg.github.com
      - npm install
      - npm install @angular/cli -g
      - find -maxdepth 4 -path "./projects/*" -name "package.json" | while read file; do sed "s|version_undefined|${DRONE_TAG##v}|g" -i $file; done
      - make libraries
      - echo "Built Version ${DRONE_TAG##v}"
    depends_on: [imagebuild]


  - name: ngx-neops-app-components
    image: plugins/npm
    settings:
      username: { from_secret: npm_username }
      password: { from_secret: npm_password }
      token: { from_secret: npm_token }
      email: release@neops.io
      registry: "https://npm.pkg.github.com"
      folder: dist/zebbra/ngx-neops-app-components
    depends_on: [make]

  - name: ngx-neops-app-services
    image: plugins/npm
    settings:
      username: { from_secret: npm_username }
      password: { from_secret: npm_password }
      token: { from_secret: npm_token }
      email: release@neops.io
      registry: "https://npm.pkg.github.com"
      folder: dist/zebbra/ngx-neops-app-services
    depends_on: [make]

  - name: ngx-neops-client
    image: plugins/npm
    settings:
      username: { from_secret: npm_username }
      password: { from_secret: npm_password }
      token: { from_secret: npm_token }
      email: release@neops.io
      registry: "https://npm.pkg.github.com"
      folder: dist/zebbra/ngx-neops-client
    depends_on: [make]

  - name: ngx-neops-dashboard
    image: plugins/npm
    settings:
      username: { from_secret: npm_username }
      password: { from_secret: npm_password }
      token: { from_secret: npm_token }
      email: release@neops.io
      registry: "https://npm.pkg.github.com"
      folder: dist/zebbra/ngx-neops-dashboard
    depends_on: [make]

  - name: ngx-neops-generic-table
    image: plugins/npm
    settings:
      username: { from_secret: npm_username }
      password: { from_secret: npm_password }
      token: { from_secret: npm_token }
      email: release@neops.io
      registry: "https://npm.pkg.github.com"
      folder: dist/zebbra/ngx-neops-generic-table
    depends_on: [make]
